# API Keys
OPENAI_API_KEY = "your-openai-api-key-here" # Your OpenAI API key
GROQ_API_KEY = "your-groq-api-key-here"
NEWSAPI_KEY = "your-newsapi-key-here"
FINNHUB_API_KEY = "your-finnhub-api-key-here"
GNEWS_API_KEY = "your-gnews-api-key-here"

# Database configuration
[database]
AZURE_DATABASE = "your-database-name"
AZURE_HOSTNAME = "your-hostname.mysql.database.azure.com"
AZURE_PASSWORD = "your-password"
AZURE_USER = "your-username"
AZURE_PORT = "3306"
AZURE_CERT = "your-azure-certificate-here" 